disabled_rules: 
 - trailing_whitespace
 - weak_delegate
 - class_delegate_protocol
 - empty_enum_arguments
 - large_tuple
 - multiple_closures_with_trailing_closure
 - cyclomatic_complexity
 - force_cast
 - force_try
 - legacy_constant
 - legacy_constructor

line_length: 
  warning: 200
  error: 300
  ignores_comments: true

function_body_length:
  warning: 150
  error: 300

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 2
  max_length:
    warning: 60
    error: 100

identifier_name:
  min_length: 1
  allowed_symbols: "_"
  excluded: # excluded via string array
    - id
    - URL
    - API
    - CSD
    
excluded:
  - Pods/
  - scripts/
  - reports/
