# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp
  pod 'SwiftLint', '0.39.2'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'AlamofireNetworkActivityLogger', '~> 3.0'
  pod 'GoogleMaps', '3.7.0'
  pod 'MaterialComponents/Snackbar', '93.3.0'
  pod 'SDWebImage', '~> 5.0'
end
