# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp
  pod 'SwiftLint', '0.42.0'
  pod 'Alamofire', '5.4.1'
  pod 'AlamofireNetworkActivityLogger', '~> 3.4'
  pod 'GoogleMaps', '4.1.0'
  pod 'MaterialComponents/Snackbar', '93.3.0'
  pod 'SDWebImage', '5.10.4'
end
